### ISSUE TITLE
TypeScript 2.X support?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sagifogel/typescript-closure-compiler#2]
Are there plans to upgrade the compatibility version to TS 2? If not, is there a guide to doing so?

**Comment by sagifogel** [comment]
Yes, But it might take a while to finish it.

**Comment by JoshuaKGoldberg** [comment]
Ok. Are there issues tracking it or documentation that can help newcomers to assist?

**Comment by sagifogel** [comment]
No, if you want to contribute please send me an email so we can discuss it extensively.

**Comment by jjrv** [comment]
You might want to check out this project from Google: https://github.com/angular/tsickle

**Comment by JoshuaKGoldberg** [comment]
I am very curious about why both projects exist, especially given that tsickle seems to be much more supported.

**Comment by jjrv** [comment]
Maybe `tsickle` has been more difficult to find, and not yet working before. I haven't actually tried either project, just watching them for future use.

**Comment by sagifogel** [comment]
History:
About 1.5 years ago I decided to write TypeScript instead of vanilla js, so I needed to find a plovr/closure compiler annotator (for TypeScript 1.7).
I searched for it and found this repository.
This was the only solution for minifing TypeScript  artifacts using closure compiler.
[Evan Wallace](https://github.com/evanw) was the creator of this project. 
His last supported version was TypeScript 0.91. 
I asked him to give me ownership over this project, and created two branches for 1.7 and 1.8. 

`tsickle` aims to do the same thing but focuses on angular.
At work we wanted to start using `tsickle` because a team of developers (tsickle team) can deliver much faster than one man (Myself).
Eventually, we continued to work with `typescript-closure-compiler` because we could not make it work as an angular free solution.
We've opened an issue for them [374](https://github.com/angular/tsickle/issues/374) however, we do not have a time estimate as to when they will take care of it.
